// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.gin.hbase;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyPhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string opponentPhone = 1;
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    boolean hasOpponentPhone();
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    java.lang.String getOpponentPhone();
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    com.google.protobuf.ByteString
        getOpponentPhoneBytes();

    // required string connectTime = 2;
    /**
     * <code>required string connectTime = 2;</code>
     */
    boolean hasConnectTime();
    /**
     * <code>required string connectTime = 2;</code>
     */
    java.lang.String getConnectTime();
    /**
     * <code>required string connectTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getConnectTimeBytes();

    // required string date = 3;
    /**
     * <code>required string date = 3;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 3;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 3;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // required string type = 4;
    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.gin.hbase.MyPhoneDetail}
   */
  public static final class MyPhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements MyPhoneDetailOrBuilder {
    // Use MyPhoneDetail.newBuilder() to construct.
    private MyPhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyPhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyPhoneDetail defaultInstance;
    public static MyPhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public MyPhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyPhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              opponentPhone_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              connectTime_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              date_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gin.hbase.Phone.internal_static_com_gin_hbase_MyPhoneDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gin.hbase.Phone.internal_static_com_gin_hbase_MyPhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gin.hbase.Phone.MyPhoneDetail.class, com.gin.hbase.Phone.MyPhoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<MyPhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<MyPhoneDetail>() {
      public MyPhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyPhoneDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyPhoneDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string opponentPhone = 1;
    public static final int OPPONENTPHONE_FIELD_NUMBER = 1;
    private java.lang.Object opponentPhone_;
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    public boolean hasOpponentPhone() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    public java.lang.String getOpponentPhone() {
      java.lang.Object ref = opponentPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          opponentPhone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string opponentPhone = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOpponentPhoneBytes() {
      java.lang.Object ref = opponentPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        opponentPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string connectTime = 2;
    public static final int CONNECTTIME_FIELD_NUMBER = 2;
    private java.lang.Object connectTime_;
    /**
     * <code>required string connectTime = 2;</code>
     */
    public boolean hasConnectTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string connectTime = 2;</code>
     */
    public java.lang.String getConnectTime() {
      java.lang.Object ref = connectTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          connectTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string connectTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConnectTimeBytes() {
      java.lang.Object ref = connectTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 3;
    public static final int DATE_FIELD_NUMBER = 3;
    private java.lang.Object date_;
    /**
     * <code>required string date = 3;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string date = 3;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      opponentPhone_ = "";
      connectTime_ = "";
      date_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOpponentPhone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConnectTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOpponentPhoneBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getConnectTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOpponentPhoneBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getConnectTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gin.hbase.Phone.MyPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gin.hbase.Phone.MyPhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gin.hbase.MyPhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gin.hbase.Phone.MyPhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gin.hbase.Phone.internal_static_com_gin_hbase_MyPhoneDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gin.hbase.Phone.internal_static_com_gin_hbase_MyPhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gin.hbase.Phone.MyPhoneDetail.class, com.gin.hbase.Phone.MyPhoneDetail.Builder.class);
      }

      // Construct using com.gin.hbase.Phone.MyPhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        opponentPhone_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        connectTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gin.hbase.Phone.internal_static_com_gin_hbase_MyPhoneDetail_descriptor;
      }

      public com.gin.hbase.Phone.MyPhoneDetail getDefaultInstanceForType() {
        return com.gin.hbase.Phone.MyPhoneDetail.getDefaultInstance();
      }

      public com.gin.hbase.Phone.MyPhoneDetail build() {
        com.gin.hbase.Phone.MyPhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gin.hbase.Phone.MyPhoneDetail buildPartial() {
        com.gin.hbase.Phone.MyPhoneDetail result = new com.gin.hbase.Phone.MyPhoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opponentPhone_ = opponentPhone_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.connectTime_ = connectTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gin.hbase.Phone.MyPhoneDetail) {
          return mergeFrom((com.gin.hbase.Phone.MyPhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gin.hbase.Phone.MyPhoneDetail other) {
        if (other == com.gin.hbase.Phone.MyPhoneDetail.getDefaultInstance()) return this;
        if (other.hasOpponentPhone()) {
          bitField0_ |= 0x00000001;
          opponentPhone_ = other.opponentPhone_;
          onChanged();
        }
        if (other.hasConnectTime()) {
          bitField0_ |= 0x00000002;
          connectTime_ = other.connectTime_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000004;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpponentPhone()) {
          
          return false;
        }
        if (!hasConnectTime()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gin.hbase.Phone.MyPhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gin.hbase.Phone.MyPhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string opponentPhone = 1;
      private java.lang.Object opponentPhone_ = "";
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public boolean hasOpponentPhone() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public java.lang.String getOpponentPhone() {
        java.lang.Object ref = opponentPhone_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          opponentPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOpponentPhoneBytes() {
        java.lang.Object ref = opponentPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          opponentPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public Builder setOpponentPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        opponentPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public Builder clearOpponentPhone() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opponentPhone_ = getDefaultInstance().getOpponentPhone();
        onChanged();
        return this;
      }
      /**
       * <code>required string opponentPhone = 1;</code>
       */
      public Builder setOpponentPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        opponentPhone_ = value;
        onChanged();
        return this;
      }

      // required string connectTime = 2;
      private java.lang.Object connectTime_ = "";
      /**
       * <code>required string connectTime = 2;</code>
       */
      public boolean hasConnectTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string connectTime = 2;</code>
       */
      public java.lang.String getConnectTime() {
        java.lang.Object ref = connectTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          connectTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string connectTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConnectTimeBytes() {
        java.lang.Object ref = connectTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connectTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string connectTime = 2;</code>
       */
      public Builder setConnectTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        connectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string connectTime = 2;</code>
       */
      public Builder clearConnectTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        connectTime_ = getDefaultInstance().getConnectTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string connectTime = 2;</code>
       */
      public Builder setConnectTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        connectTime_ = value;
        onChanged();
        return this;
      }

      // required string date = 3;
      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 3;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string date = 3;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 3;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        date_ = value;
        onChanged();
        return this;
      }

      // required string type = 4;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gin.hbase.MyPhoneDetail)
    }

    static {
      defaultInstance = new MyPhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gin.hbase.MyPhoneDetail)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gin_hbase_MyPhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gin_hbase_MyPhoneDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\022\rcom.gin.hbase\"W\n\rMyPhoneD" +
      "etail\022\025\n\ropponentPhone\030\001 \002(\t\022\023\n\013connectT" +
      "ime\030\002 \002(\t\022\014\n\004date\030\003 \002(\t\022\014\n\004type\030\004 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_gin_hbase_MyPhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_gin_hbase_MyPhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gin_hbase_MyPhoneDetail_descriptor,
              new java.lang.String[] { "OpponentPhone", "ConnectTime", "Date", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
